//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderTaker.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderTaker.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string ConversionFromDollar {
            get {
                return ResourceManager.GetString("ConversionFromDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain&apos;s Chair (Vinyl).
        /// </summary>
        public static string Product_CaptainsChairVinyl {
            get {
                return ResourceManager.GetString("Product_CaptainsChairVinyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain&apos;s Chair (Leather).
        /// </summary>
        public static string Product_CaptiainsChairLeather {
            get {
                return ResourceManager.GetString("Product_CaptiainsChairLeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Beacon.
        /// </summary>
        public static string Product_LaserBeacon {
            get {
                return ResourceManager.GetString("Product_LaserBeacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moonbase.
        /// </summary>
        public static string Product_Moonbase {
            get {
                return ResourceManager.GetString("Product_Moonbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Badge: {0}.
        /// </summary>
        public static string Product_NameBadge {
            get {
                return ResourceManager.GetString("Product_NameBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Suit.
        /// </summary>
        public static string Product_SpaceSuit {
            get {
                return ResourceManager.GetString("Product_SpaceSuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starship.
        /// </summary>
        public static string Product_Starship {
            get {
                return ResourceManager.GetString("Product_Starship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Translator.
        /// </summary>
        public static string Product_UniversalTranslator {
            get {
                return ResourceManager.GetString("Product_UniversalTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warp Engine.
        /// </summary>
        public static string Product_WarpEngine {
            get {
                return ResourceManager.GetString("Product_WarpEngine", resourceCulture);
            }
        }
    }
}
