//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderTaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderTaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer:.
        /// </summary>
        public static string MainWindow_Customer_Customer {
            get {
                return ResourceManager.GetString("MainWindow_Customer_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Since:.
        /// </summary>
        public static string MainWindow_Customer_CustomerSince {
            get {
                return ResourceManager.GetString("MainWindow_Customer_CustomerSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string MainWindow_Customer_Rating {
            get {
                return ResourceManager.GetString("MainWindow_Customer_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount:.
        /// </summary>
        public static string MainWindow_Order_Discount {
            get {
                return ResourceManager.GetString("MainWindow_Order_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Order.
        /// </summary>
        public static string MainWindow_Order_SubmitOrder {
            get {
                return ResourceManager.GetString("MainWindow_Order_SubmitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string MainWindow_Order_Total {
            get {
                return ResourceManager.GetString("MainWindow_Order_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string MainWindow_Product_AddItem {
            get {
                return ResourceManager.GetString("MainWindow_Product_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product:.
        /// </summary>
        public static string MainWindow_Product_Product {
            get {
                return ResourceManager.GetString("MainWindow_Product_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        public static string MainWindow_Product_Quantity {
            get {
                return ResourceManager.GetString("MainWindow_Product_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price:.
        /// </summary>
        public static string MainWindow_Product_UnitPrice {
            get {
                return ResourceManager.GetString("MainWindow_Product_UnitPrice", resourceCulture);
            }
        }
    }
}
